# Generated by Django 6.0.2 on 2026-03-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chitfund', '0002_alter_client_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='is_active',
        ),
        migrations.AddField(
            model_name='client',
            name='lifted_month',
            field=models.DateField(blank=True, help_text='Set as first day of month. Example: 2026-03-01.', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('NOT_LIFTED', 'Not Lifted'), ('LIFTED', 'Lifted')], default='NOT_LIFTED', max_length=20),
        ),
    ]
