# Generated by Codex on 2026-05-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chitfund", "0005_client_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="chit_fund",
            field=models.CharField(
                choices=[
                    ("FIVE_LAKH", "5 lakh chitti"),
                    ("TWO_LAKH", "2 lakh chitti"),
                    ("NEW_TWO_LAKH", "new 2 lakh chitti"),
                ],
                default="TWO_LAKH",
                max_length=20,
            ),
        ),
    ]
