# Generated by Django 6.0.3 on 2026-05-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chitfund', '0006_client_chit_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyexpense',
            name='category',
            field=models.CharField(choices=[('PERSONAL', 'Personal expenses'), ('HOME', 'Home expenses')], default='PERSONAL', max_length=80),
        ),
    ]
