# Generated by Django 6.0.3 on 2026-06-02 13:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chitfund', '0008_creditfriend_credittransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFinanceClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('asked_amount', models.DecimalField(decimal_places=2, help_text='Total amount requested by the client (e.g. 100,000)', max_digits=10)),
                ('interest_rate_percent', models.DecimalField(decimal_places=2, default=5.0, help_text='Monthly interest rate (e.g. 5%)', max_digits=5)),
                ('duration_days', models.IntegerField(default=100, help_text='Duration of the loan in days')),
                ('interest_amount', models.DecimalField(decimal_places=2, help_text='Pre-deducted interest amount', max_digits=10)),
                ('given_amount', models.DecimalField(decimal_places=2, help_text='Actual amount given to client (asked_amount - interest_amount)', max_digits=10)),
                ('daily_installment', models.DecimalField(decimal_places=2, help_text='Daily installment amount (asked_amount / duration_days)', max_digits=10)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(help_text='Expected completion date')),
                ('is_active', models.BooleanField(default=True, help_text='Is the loan currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_finance_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DailyFinancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid'), ('PARTIAL', 'Partial')], default='PAID', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='chitfund.dailyfinanceclient')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('client', 'date')},
            },
        ),
    ]
